apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service-k8s
spec:
  selector:
    matchLabels:
      app: worker-service-k8s
  template:
    metadata:
      labels:
        app: worker-service-k8s
    spec:
      containers:
      - name: worker-service-k8s
        imagePullPolicy: IfNotPresent
        image: worker-service-k8s:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"    
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          failureThreshold: 2
          timeoutSeconds: 3
          periodSeconds: 20
        
